# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: bgp-and-redistribution-configure
# label used for menu selection
label: bgp-and-redistribution-configure
description: This skillet will configure BGP and a redistribution profile

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - myCollection

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: hostname
    description: Firewall hostname
    default: myFirewall
    type_hint: text
# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: bgp
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/virtual-router
    file: bgp.xml
# ---------------------------------------------------------------------
# end of snippets section
